---
title: "Second Try"
author: "Sydney"
date: "12/11/2018"
output: html_document
---

```{r}
library(tidyr)
library(dplyr)
library(data.table)
library(caTools)
library(randomForest)

kddata <- read.csv("kddcup.data_10_percent_corrected", stringsAsFactors=FALSE)
kddnames=read.table("kddcup.names",sep=":",skip=1,as.is=T)
colnames(kddata)=c(kddnames[,1],"normal")
```

```{r}
kddata["effect"] <- NA
```

```{r}
for (j in 1:nrow(kddata)){
  if (kddata$normal[j] == 'normal.'){
    kddata$effect[j] <- 'nothing'
  }
  else if (kddata$normal[j] == 'back.'){
    kddata$effect[j] <- 'slows'
  }
  else if (kddata$normal[j] == 'land.'){
    kddata$effect[j] <- 'slows'
  }
  else if (kddata$normal[j] == 'neptune.'){
    kddata$effect[j] <- 'slows'
  }
  else if (kddata$normal[j] == 'smurf.'){
    kddata$effect[j] <- 'slows'
  }
  else if (kddata$normal[j] == 'pod.'){
    kddata$effect[j] <- 'slows'
  }
  else if (kddata$normal[j] == 'teardrop.'){
    kddata$effect[j] <- 'reboots'
  }
  else if (kddata$normal[j] == 'loadmodule.'){
    kddata$effect[j] <- 'root_shell'
  }
  else if (kddata$normal[j] == 'buffer_overflow.'){
    kddata$effect[j] <- 'root_shell'
  }
  else if (kddata$normal[j] == 'rootkit.'){
    kddata$effect[j] <- 'root_shell'
  }
  else if (kddata$normal[j] == 'perl.'){
    kddata$effect[j] <- 'root_shell'
  }
  else if (kddata$normal[j] == 'phf.'){
    kddata$effect[j] <- 'executes_commands_root'
  }
  else if (kddata$normal[j] == 'guess_passwd.'){
    kddata$effect[j] <- 'user_access'
  }
  else if (kddata$normal[j] == 'warezmaster.'){
    kddata$effect[j] <- 'user_access'
  }
  else if (kddata$normal[j] == 'imap.'){
    kddata$effect[j] <- 'root_access'
  }
  else if (kddata$normal[j] == 'multihop.'){
    kddata$effect[j] <- 'root_access'
  }
  else if (kddata$normal[j] == 'ftp_write.'){
    kddata$effect[j] <- 'user_access'
  }
  else if (kddata$normal[j] == 'spy.'){
    kddata$effect[j] <- 'user_access'
  }
  else if (kddata$normal[j] == 'warezclient.'){
    kddata$effect[j] <- 'user_access'
  }
  else if (kddata$normal[j] == 'satan.'){
    kddata$effect[j] <- 'looks_known_vulnerabilities'
  }
  else if (kddata$normal[j] == 'nmap.'){
    kddata$effect[j] <- 'identifies_active_ports'
  }
  else if (kddata$normal[j] == 'portsweep.'){
    kddata$effect[j] <- 'identifies_active_ports'
  }
  else if (kddata$normal[j] == 'ipsweep.'){
    kddata$effect[j] <- 'identifies_active_machines'
  }
}
```

```{r}
kddata$protocol_type = factor(kddata$protocol_type, levels = c('icmp', 'tcp', 'udp'), labels = c(1, 2, 3))
kddata$service = factor(kddata$service, labels = c(1:66))
kddata$normal = factor(kddata$normal, labels = c(1:23))
kddata$flag = factor(kddata$flag, labels = c(1:11))
kddata$effect = factor(kddata$effect, labels = c(1:10))
```

```{r}
for (i in 1:42) {
  kddata[i] <- mutate_all(kddata[i], function(x) as.numeric(as.character(x)))
}
kddata[-43] = scale(kddata[-43])
kddata <- kddata[-21]
kddata <- kddata[-20]
```

```{r}
library(caTools)
set.seed(123)
split = sample.split(kddata$effect, SplitRatio = 0.25)
training_set = subset(kddata, split == TRUE)
test_set = subset(kddata, split == FALSE)
```

```{r}
classifier1 = randomForest(x = training_set[,-41], y = training_set$effect, ntree=500)
```

```{r}
ypred1 = predict(classifier1, newdata = test_set[,-41])
cm1 = table(test_set[,41], ypred1)
cm1
```

```{r}
Accuracy11 = 0

for (i in 1:10){
  Accuracy11 = Accuracy11 + cm1[i, i]
}

Accuracy12 = 0

for (i in 1:10){
  for (j in 1:10){
    Accuracy12 = Accuracy12 + cm1[i, j]
  }
}

Accuracy1 = Accuracy11/Accuracy12
Accuracy1
```







