---
title: "Third Try"
author: "Sydney"
date: "12/12/2018"
output: html_document
---

```{r}
library(tidyr)
library(dplyr)
library(data.table)
library(caTools)
library(randomForest)

kddata <- read.csv("kddcup.data_10_percent_corrected", stringsAsFactors=FALSE)
kddnames=read.table("kddcup.names",sep=":",skip=1,as.is=T)
colnames(kddata)=c(kddnames[,1],"normal")
```

```{r}
kddata["effect"] <- NA
```

```{r}
for (j in 1:nrow(kddata)){
  if (kddata$normal[j] == 'normal.'){
    kddata$effect[j] <- 'nothing'
  }
  else if (kddata$normal[j] == 'back.'){
    kddata$effect[j] <- 'slows'
  }
  else if (kddata$normal[j] == 'land.'){
    kddata$effect[j] <- 'slows'
  }
  else if (kddata$normal[j] == 'neptune.'){
    kddata$effect[j] <- 'slows'
  }
  else if (kddata$normal[j] == 'smurf.'){
    kddata$effect[j] <- 'slows'
  }
  else if (kddata$normal[j] == 'pod.'){
    kddata$effect[j] <- 'slows'
  }
  else if (kddata$normal[j] == 'teardrop.'){
    kddata$effect[j] <- 'reboots'
  }
  else if (kddata$normal[j] == 'loadmodule.'){
    kddata$effect[j] <- 'root_shell'
  }
  else if (kddata$normal[j] == 'buffer_overflow.'){
    kddata$effect[j] <- 'root_shell'
  }
  else if (kddata$normal[j] == 'rootkit.'){
    kddata$effect[j] <- 'root_shell'
  }
  else if (kddata$normal[j] == 'perl.'){
    kddata$effect[j] <- 'root_shell'
  }
  else if (kddata$normal[j] == 'phf.'){
    kddata$effect[j] <- 'executes_commands_root'
  }
  else if (kddata$normal[j] == 'guess_passwd.'){
    kddata$effect[j] <- 'user_access'
  }
  else if (kddata$normal[j] == 'warezmaster.'){
    kddata$effect[j] <- 'user_access'
  }
  else if (kddata$normal[j] == 'imap.'){
    kddata$effect[j] <- 'root_access'
  }
  else if (kddata$normal[j] == 'multihop.'){
    kddata$effect[j] <- 'root_access'
  }
  else if (kddata$normal[j] == 'ftp_write.'){
    kddata$effect[j] <- 'user_access'
  }
  else if (kddata$normal[j] == 'spy.'){
    kddata$effect[j] <- 'user_access'
  }
  else if (kddata$normal[j] == 'warezclient.'){
    kddata$effect[j] <- 'user_access'
  }
  else if (kddata$normal[j] == 'satan.'){
    kddata$effect[j] <- 'looks_known_vulnerabilities'
  }
  else if (kddata$normal[j] == 'nmap.'){
    kddata$effect[j] <- 'identifies_active_ports'
  }
  else if (kddata$normal[j] == 'portsweep.'){
    kddata$effect[j] <- 'identifies_active_ports'
  }
  else if (kddata$normal[j] == 'ipsweep.'){
    kddata$effect[j] <- 'identifies_active_machines'
  }
}
```

```{r}
kddata1 <- kddata
for (j in 1:nrow(kddata1)){
  if (kddata1$effect[j] == 'nothing'){
    kddata1$effect[j] <- -1
  }
  else if (kddata1$effect[j] == 'slows'){
    kddata1$effect[j] <- -1
  }
  else if (kddata1$effect[j] == 'reboots'){
    kddata1$effect[j] <- -1
  }
  else if (kddata1$effect[j] == 'root_shell'){
    kddata1$effect[j] <- 1
  }
  else if (kddata1$effect[j] == 'executes_commands_root'){
    kddata1$effect[j] <- 1
  }
  else if (kddata1$effect[j] == 'user_access'){
    kddata1$effect[j] <- 1
  }
  else if (kddata1$effect[j] == 'root_access'){
    kddata1$effect[j] <- 1
  }
  else if (kddata1$effect[j] == 'looks_known_vulnerabilities'){
    kddata1$effect[j] <- -1
  }
  else if (kddata1$effect[j] == 'identifies_active_ports'){
    kddata1$effect[j] <- -1
  }
  else if (kddata1$effect[j] == 'identifies_active_machines'){
    kddata1$effect[j] <- -1
  }
}
```

```{r}
kddata1$protocol_type = factor(kddata1$protocol_type, levels = c('icmp', 'tcp', 'udp'), labels = c(1, 2, 3))
kddata1$service = factor(kddata1$service, labels = c(1:66))
kddata1$normal = factor(kddata1$normal, labels = c(1:23))
kddata1$flag = factor(kddata1$flag, labels = c(1:11))
```

```{r}
for (i in 1:42) {
  kddata1[i] <- mutate_all(kddata1[i], function(x) as.numeric(as.character(x)))
}
kddata1[-43] = scale(kddata1[-43])
kddata1 <- kddata1[-21]
kddata1 <- kddata1[-20]
```

```{r}
set.seed(123456)
dataindex = c(1:dim(kddata1)[1])
oneFifth = ceiling((dim(kddata1)[1])/5)
fifthRange = c(1:oneFifth)
jumbledIndex = sample(dataindex,dim(kddata1)[1],replace=F)
kddatatestlist1 = jumbledIndex[fifthRange]
kddatatestlist5 = jumbledIndex[-fifthRange]
kddatatestlist2 = kddatatestlist5[fifthRange]
kddatatestlist5 = kddatatestlist5[-fifthRange]
kddatatestlist3 = kddatatestlist5[fifthRange]
kddatatestlist5 = kddatatestlist5[-fifthRange]
kddatatestlist4 = kddatatestlist5[fifthRange]
kddatatestlist5 = kddatatestlist5[-fifthRange]

testset1 = kddata1[kddatatestlist1,]
trainingset1 = kddata1[-kddatatestlist1,]
testset2 = kddata1[kddatatestlist2,]
trainingset2 = kddata1[-kddatatestlist2,]
testset3 = kddata1[kddatatestlist3,]
trainingset3 = kddata1[-kddatatestlist3,]
testset4 = kddata1[kddatatestlist4,]
trainingset4 = kddata1[-kddatatestlist4,]
testset5 = kddata1[kddatatestlist5,]
trainingset5 = kddata1[-kddatatestlist5,]
```

```{r}
library(fastAdaboost)
classifier1 <- adaboost(effect ~ ., trainingset1, nIter = 5)
classifier2 <- adaboost(effect ~ ., trainingset2, nIter = 5)
classifier3 <- adaboost(effect ~ ., trainingset3, nIter = 5)
classifier4 <- adaboost(effect ~ ., trainingset4, nIter = 5)
classifier5 <- adaboost(effect ~ ., trainingset5, nIter = 5)

```

```{r}
ypred1 = predict(classifier1, newdata = testset1[-41])
ypred2 = predict(classifier2, newdata = testset2[-41])
ypred3 = predict(classifier3, newdata = testset3[-41])
ypred4 = predict(classifier4, newdata = testset4[-41])
ypred5 = predict(classifier5, newdata = testset5[-41])
```

```{r}
cm1 = table(testset1[, 41], ypred1$class)
cm2 = table(testset2[, 41], ypred2$class)
cm3 = table(testset3[, 41], ypred3$class)
cm4 = table(testset4[, 41], ypred4$class)
cm5 = table(testset5[, 41], ypred5$class)
cm1
cm2
cm3
cm4
cm5
```

```{r}
Accuracy1 <- (cm1[1,1] + cm1[2,2])/(cm1[1,1] + cm1[1,2] + cm1[2,1] + cm1[2,2])
Accuracy2 <- (cm2[1,1] + cm2[2,2])/(cm2[1,1] + cm2[1,2] + cm2[2,1] + cm2[2,2])
Accuracy3 <- (cm3[1,1] + cm3[2,2])/(cm3[1,1] + cm3[1,2] + cm3[2,1] + cm3[2,2])
Accuracy4 <- (cm4[1,1] + cm4[2,2])/(cm4[1,1] + cm4[1,2] + cm4[2,1] + cm4[2,2])
Accuracy5 <- (cm5[1,1] + cm5[2,2])/(cm5[1,1] + cm5[1,2] + cm5[2,1] + cm5[2,2])
Accuracy1
Accuracy2
Accuracy3
Accuracy4
Accuracy5
```

```{r}
library(pROC)
ROC1 <- roc(testset1[, 41], ypred1$class)
ROC2 <- roc(testset2[, 41], ypred2$class)
ROC3 <- roc(testset3[, 41], ypred3$class)
ROC4 <- roc(testset4[, 41], ypred4$class)
ROC5 <- roc(testset5[, 41], ypred5$class)
```

```{r}
kddata2 <- kddata
```







